// <auto-generated />
namespace ThucTapNhom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_price_to_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_price_to_int));
        
        string IMigrationMetadata.Id
        {
            get { return "202006301601354_change_price_to_int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
